import {normalizeCommits, normalizeRepos} from './fetchData';
import {expect} from 'chai';

it('normalizes repos', () => {
  const repoPayload = {
    items: [
      {
        id: 28457823,
        node_id: 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
        name: 'freeCodeCamp',
        full_name: 'freeCodeCamp/freeCodeCamp',
        private: false,
        owner: {
          login: 'freeCodeCamp',
          id: 9892522,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
          avatar_url: 'https://avatars0.githubusercontent.com/u/9892522?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/freeCodeCamp',
          html_url: 'https://github.com/freeCodeCamp',
          followers_url: 'https://api.github.com/users/freeCodeCamp/followers',
          following_url: 'https://api.github.com/users/freeCodeCamp/following{/other_user}',
          gists_url: 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/freeCodeCamp/subscriptions',
          organizations_url: 'https://api.github.com/users/freeCodeCamp/orgs',
          repos_url: 'https://api.github.com/users/freeCodeCamp/repos',
          events_url: 'https://api.github.com/users/freeCodeCamp/events{/privacy}',
          received_events_url: 'https://api.github.com/users/freeCodeCamp/received_events',
          type: 'Organization',
          site_admin: false,
        },
        html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
        description:
          'The https://www.freeCodeCamp.org open source codebase and curriculum. Learn to code for free together with millions of people.',
        fork: false,
        url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp',
        forks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/forks',
        keys_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/teams',
        hooks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/hooks',
        issue_events_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/events{/number}',
        events_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/events',
        assignees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/assignees{/user}',
        branches_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/branches{/branch}',
        tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/tags',
        blobs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/languages',
        stargazers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/stargazers',
        contributors_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contributors',
        subscribers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscribers',
        subscription_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscription',
        commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contents/{+path}',
        compare_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/merges',
        archive_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/downloads',
        issues_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues{/number}',
        pulls_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/labels{/name}',
        releases_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/releases{/id}',
        deployments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/deployments',
        created_at: '2014-12-24T17:49:19Z',
        updated_at: '2019-10-20T18:12:13Z',
        pushed_at: '2019-10-20T17:33:08Z',
        git_url: 'git://github.com/freeCodeCamp/freeCodeCamp.git',
        ssh_url: 'git@github.com:freeCodeCamp/freeCodeCamp.git',
        clone_url: 'https://github.com/freeCodeCamp/freeCodeCamp.git',
        svn_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
        homepage: '',
        size: 120839,
        stargazers_count: 305692,
        watchers_count: 305692,
        language: 'JavaScript',
        has_issues: true,
        has_projects: false,
        has_downloads: true,
        has_wiki: false,
        has_pages: false,
        forks_count: 22970,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 322,
        license: {
          key: 'bsd-3-clause',
          name: 'BSD 3-Clause "New" or "Revised" License',
          spdx_id: 'BSD-3-Clause',
          url: 'https://api.github.com/licenses/bsd-3-clause',
          node_id: 'MDc6TGljZW5zZTU=',
        },
        forks: 22970,
        open_issues: 322,
        watchers: 305692,
        default_branch: 'master',
        score: 1,
      },
      {
        id: 177736533,
        node_id: 'MDEwOlJlcG9zaXRvcnkxNzc3MzY1MzM=',
        name: '996.ICU',
        full_name: '996icu/996.ICU',
        private: false,
        owner: {
          login: '996icu',
          id: 48942249,
          node_id: 'MDQ6VXNlcjQ4OTQyMjQ5',
          avatar_url: 'https://avatars3.githubusercontent.com/u/48942249?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/996icu',
          html_url: 'https://github.com/996icu',
          followers_url: 'https://api.github.com/users/996icu/followers',
          following_url: 'https://api.github.com/users/996icu/following{/other_user}',
          gists_url: 'https://api.github.com/users/996icu/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/996icu/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/996icu/subscriptions',
          organizations_url: 'https://api.github.com/users/996icu/orgs',
          repos_url: 'https://api.github.com/users/996icu/repos',
          events_url: 'https://api.github.com/users/996icu/events{/privacy}',
          received_events_url: 'https://api.github.com/users/996icu/received_events',
          type: 'User',
          site_admin: false,
        },
        html_url: 'https://github.com/996icu/996.ICU',
        description: 'Repo for counting stars and contributing. Press F to pay respect to glorious developers.',
        fork: false,
        url: 'https://api.github.com/repos/996icu/996.ICU',
        forks_url: 'https://api.github.com/repos/996icu/996.ICU/forks',
        keys_url: 'https://api.github.com/repos/996icu/996.ICU/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/996icu/996.ICU/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/996icu/996.ICU/teams',
        hooks_url: 'https://api.github.com/repos/996icu/996.ICU/hooks',
        issue_events_url: 'https://api.github.com/repos/996icu/996.ICU/issues/events{/number}',
        events_url: 'https://api.github.com/repos/996icu/996.ICU/events',
        assignees_url: 'https://api.github.com/repos/996icu/996.ICU/assignees{/user}',
        branches_url: 'https://api.github.com/repos/996icu/996.ICU/branches{/branch}',
        tags_url: 'https://api.github.com/repos/996icu/996.ICU/tags',
        blobs_url: 'https://api.github.com/repos/996icu/996.ICU/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/996icu/996.ICU/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/996icu/996.ICU/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/996icu/996.ICU/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/996icu/996.ICU/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/996icu/996.ICU/languages',
        stargazers_url: 'https://api.github.com/repos/996icu/996.ICU/stargazers',
        contributors_url: 'https://api.github.com/repos/996icu/996.ICU/contributors',
        subscribers_url: 'https://api.github.com/repos/996icu/996.ICU/subscribers',
        subscription_url: 'https://api.github.com/repos/996icu/996.ICU/subscription',
        commits_url: 'https://api.github.com/repos/996icu/996.ICU/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/996icu/996.ICU/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/996icu/996.ICU/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/996icu/996.ICU/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/996icu/996.ICU/contents/{+path}',
        compare_url: 'https://api.github.com/repos/996icu/996.ICU/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/996icu/996.ICU/merges',
        archive_url: 'https://api.github.com/repos/996icu/996.ICU/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/996icu/996.ICU/downloads',
        issues_url: 'https://api.github.com/repos/996icu/996.ICU/issues{/number}',
        pulls_url: 'https://api.github.com/repos/996icu/996.ICU/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/996icu/996.ICU/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/996icu/996.ICU/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/996icu/996.ICU/labels{/name}',
        releases_url: 'https://api.github.com/repos/996icu/996.ICU/releases{/id}',
        deployments_url: 'https://api.github.com/repos/996icu/996.ICU/deployments',
        created_at: '2019-03-26T07:31:14Z',
        updated_at: '2019-10-20T15:09:43Z',
        pushed_at: '2019-10-20T14:26:49Z',
        git_url: 'git://github.com/996icu/996.ICU.git',
        ssh_url: 'git@github.com:996icu/996.ICU.git',
        clone_url: 'https://github.com/996icu/996.ICU.git',
        svn_url: 'https://github.com/996icu/996.ICU',
        homepage: 'https://996.icu',
        size: 183401,
        stargazers_count: 247485,
        watchers_count: 247485,
        language: 'Rust',
        has_issues: false,
        has_projects: false,
        has_downloads: true,
        has_wiki: false,
        has_pages: false,
        forks_count: 21238,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 16741,
        license: {
          key: 'other',
          name: 'Other',
          spdx_id: 'NOASSERTION',
          url: null,
          node_id: 'MDc6TGljZW5zZTA=',
        },
        forks: 21238,
        open_issues: 16741,
        watchers: 247485,
        default_branch: 'master',
        score: 1,
      },
    ],
  };

  const expectedResult = {
    '28457823': {
      stargazers_count: 305692,
      name: 'freeCodeCamp',
      html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
      id: 28457823,
      forks_count: 22970,
      img_url: 'https://avatars0.githubusercontent.com/u/9892522?v=4',
      commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}',
    },
    '177736533': {
      stargazers_count: 247485,
      name: '996.ICU',
      html_url: 'https://github.com/996icu/996.ICU',
      id: 177736533,
      forks_count: 21238,
      img_url: 'https://avatars3.githubusercontent.com/u/48942249?v=4',
      commits_url: 'https://api.github.com/repos/996icu/996.ICU/commits{/sha}',
    },
  };

  const normalizedRepos = normalizeRepos(repoPayload);
  expect(normalizedRepos).to.deep.equal(expectedResult);
});

it('normalizes commits', () => {
  const commitsPayload = [
    {
      sha: 'e4a26c9a74c2481511f4edcdb146ee007c86c964',
      node_id: 'MDY6Q29tbWl0Mjg0NTc4MjM6ZTRhMjZjOWE3NGMyNDgxNTExZjRlZGNkYjE0NmVlMDA3Yzg2Yzk2NA==',
      commit: {
        author: {
          name: 'Ricky Syamsi',
          email: 'rickysyamsi@protonmail.com',
          date: '2019-10-20T11:01:13Z',
        },
        committer: {
          name: 'mrugesh',
          email: '1884376+raisedadead@users.noreply.github.com',
          date: '2019-10-20T11:01:13Z',
        },
        message: 'fix(client): Email and internet presence client validation (#37389)',
        tree: {
          sha: '6d75ff9dcb8bb890a93c83e54a57655f45a03ea3',
          url:
            'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees/6d75ff9dcb8bb890a93c83e54a57655f45a03ea3',
        },
        url:
          'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits/e4a26c9a74c2481511f4edcdb146ee007c86c964',
        comment_count: 0,
        verification: {
          verified: false,
          reason: 'unsigned',
          signature: null,
          payload: null,
        },
      },
      url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/e4a26c9a74c2481511f4edcdb146ee007c86c964',
      html_url: 'https://github.com/freeCodeCamp/freeCodeCamp/commit/e4a26c9a74c2481511f4edcdb146ee007c86c964',
      comments_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/e4a26c9a74c2481511f4edcdb146ee007c86c964/comments',
      author: {
        login: 'rickysyamsi',
        id: 54201112,
        node_id: 'MDQ6VXNlcjU0MjAxMTEy',
        avatar_url: 'https://avatars0.githubusercontent.com/u/54201112?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/rickysyamsi',
        html_url: 'https://github.com/rickysyamsi',
        followers_url: 'https://api.github.com/users/rickysyamsi/followers',
        following_url: 'https://api.github.com/users/rickysyamsi/following{/other_user}',
        gists_url: 'https://api.github.com/users/rickysyamsi/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/rickysyamsi/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/rickysyamsi/subscriptions',
        organizations_url: 'https://api.github.com/users/rickysyamsi/orgs',
        repos_url: 'https://api.github.com/users/rickysyamsi/repos',
        events_url: 'https://api.github.com/users/rickysyamsi/events{/privacy}',
        received_events_url: 'https://api.github.com/users/rickysyamsi/received_events',
        type: 'User',
        site_admin: false,
      },
      committer: {
        login: 'raisedadead',
        id: 1884376,
        node_id: 'MDQ6VXNlcjE4ODQzNzY=',
        avatar_url: 'https://avatars0.githubusercontent.com/u/1884376?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/raisedadead',
        html_url: 'https://github.com/raisedadead',
        followers_url: 'https://api.github.com/users/raisedadead/followers',
        following_url: 'https://api.github.com/users/raisedadead/following{/other_user}',
        gists_url: 'https://api.github.com/users/raisedadead/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/raisedadead/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/raisedadead/subscriptions',
        organizations_url: 'https://api.github.com/users/raisedadead/orgs',
        repos_url: 'https://api.github.com/users/raisedadead/repos',
        events_url: 'https://api.github.com/users/raisedadead/events{/privacy}',
        received_events_url: 'https://api.github.com/users/raisedadead/received_events',
        type: 'User',
        site_admin: false,
      },
      parents: [
        {
          sha: '7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
          url:
            'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
          html_url: 'https://github.com/freeCodeCamp/freeCodeCamp/commit/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
        },
      ],
    },
    {
      sha: '7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
      node_id: 'MDY6Q29tbWl0Mjg0NTc4MjM6N2E2ZThlZDJkOGExYjk3NjEzYzlhZWI0MDlhY2I1NjZlNGRjNTViOQ==',
      commit: {
        author: {
          name: 'Mrugesh Mohapatra',
          email: 'me@raisedadead.com',
          date: '2019-10-20T10:45:28Z',
        },
        committer: {
          name: 'mrugesh',
          email: '1884376+raisedadead@users.noreply.github.com',
          date: '2019-10-20T10:59:56Z',
        },
        message: 'chore(client): remove unused ajax util lib',
        tree: {
          sha: '607f8d16614f3e9394ba6a4a2bcf4d3934ffdf88',
          url:
            'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees/607f8d16614f3e9394ba6a4a2bcf4d3934ffdf88',
        },
        url:
          'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
        comment_count: 0,
        verification: {
          verified: false,
          reason: 'unsigned',
          signature: null,
          payload: null,
        },
      },
      url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
      html_url: 'https://github.com/freeCodeCamp/freeCodeCamp/commit/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9',
      comments_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/7a6e8ed2d8a1b97613c9aeb409acb566e4dc55b9/comments',
      author: {
        login: 'raisedadead',
        id: 1884376,
        node_id: 'MDQ6VXNlcjE4ODQzNzY=',
        avatar_url: 'https://avatars0.githubusercontent.com/u/1884376?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/raisedadead',
        html_url: 'https://github.com/raisedadead',
        followers_url: 'https://api.github.com/users/raisedadead/followers',
        following_url: 'https://api.github.com/users/raisedadead/following{/other_user}',
        gists_url: 'https://api.github.com/users/raisedadead/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/raisedadead/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/raisedadead/subscriptions',
        organizations_url: 'https://api.github.com/users/raisedadead/orgs',
        repos_url: 'https://api.github.com/users/raisedadead/repos',
        events_url: 'https://api.github.com/users/raisedadead/events{/privacy}',
        received_events_url: 'https://api.github.com/users/raisedadead/received_events',
        type: 'User',
        site_admin: false,
      },
      committer: {
        login: 'raisedadead',
        id: 1884376,
        node_id: 'MDQ6VXNlcjE4ODQzNzY=',
        avatar_url: 'https://avatars0.githubusercontent.com/u/1884376?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/raisedadead',
        html_url: 'https://github.com/raisedadead',
        followers_url: 'https://api.github.com/users/raisedadead/followers',
        following_url: 'https://api.github.com/users/raisedadead/following{/other_user}',
        gists_url: 'https://api.github.com/users/raisedadead/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/raisedadead/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/raisedadead/subscriptions',
        organizations_url: 'https://api.github.com/users/raisedadead/orgs',
        repos_url: 'https://api.github.com/users/raisedadead/repos',
        events_url: 'https://api.github.com/users/raisedadead/events{/privacy}',
        received_events_url: 'https://api.github.com/users/raisedadead/received_events',
        type: 'User',
        site_admin: false,
      },
      parents: [
        {
          sha: '368aa688fa7b5abfda2442e2c749082898fb7da9',
          url:
            'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits/368aa688fa7b5abfda2442e2c749082898fb7da9',
          html_url: 'https://github.com/freeCodeCamp/freeCodeCamp/commit/368aa688fa7b5abfda2442e2c749082898fb7da9',
        },
      ],
    },
  ];

  const expectedResult = {
    '/freecode/freecode': {
      'MDY6Q29tbWl0Mjg0NTc4MjM6N2E2ZThlZDJkOGExYjk3NjEzYzlhZWI0MDlhY2I1NjZlNGRjNTViOQ==': {
        author_name: 'Mrugesh Mohapatra',
        date: '2019-10-20T10:45:28Z',
        id: 'MDY6Q29tbWl0Mjg0NTc4MjM6N2E2ZThlZDJkOGExYjk3NjEzYzlhZWI0MDlhY2I1NjZlNGRjNTViOQ==',
        message: 'chore(client): remove unused ajax util lib',
      },
      'MDY6Q29tbWl0Mjg0NTc4MjM6ZTRhMjZjOWE3NGMyNDgxNTExZjRlZGNkYjE0NmVlMDA3Yzg2Yzk2NA==': {
        author_name: 'Ricky Syamsi',
        date: '2019-10-20T11:01:13Z',
        id: 'MDY6Q29tbWl0Mjg0NTc4MjM6ZTRhMjZjOWE3NGMyNDgxNTExZjRlZGNkYjE0NmVlMDA3Yzg2Yzk2NA==',
        message: 'fix(client): Email and internet presence client validation (#37389)',
      },
    },
  };

  const normalizedCommits = normalizeCommits('/freecode/freecode')(commitsPayload);
  expect(normalizedCommits).to.deep.equal(expectedResult);
});
